name: "${pluginName}"
version: '${version}'
main: "org.purpurmc.purpurextras.PurpurExtrasOG"
api-version: '${apiVersion}'
authors: [ YouHaveTrouble, NotAlexNoyle ]
description: "${description}"
commands:
  purpurextras:
    description: Command controlling PurpurExtras
    permission: purpurextras.command
